// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeCBf7iAMQ5Ur7WfEZ-F799cd0X2vf498',
    appId: '1:833954155823:web:9f68076d8f6586fbbde5da',
    messagingSenderId: '833954155823',
    projectId: 'mentalzen-ammanuel',
    authDomain: 'mentalzen-ammanuel.firebaseapp.com',
    storageBucket: 'mentalzen-ammanuel.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiBX8cfzUyY-ulgXndYcxxJjwG3fIbn4M',
    appId: '1:833954155823:android:af3dd3d67bf04854bde5da',
    messagingSenderId: '833954155823',
    projectId: 'mentalzen-ammanuel',
    storageBucket: 'mentalzen-ammanuel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCClyFStHdN3I6mgkMf2MdJKrhqLMxYUpE',
    appId: '1:833954155823:ios:97ad610864d77189bde5da',
    messagingSenderId: '833954155823',
    projectId: 'mentalzen-ammanuel',
    storageBucket: 'mentalzen-ammanuel.firebasestorage.app',
    iosBundleId: 'com.example.mentalZen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCClyFStHdN3I6mgkMf2MdJKrhqLMxYUpE',
    appId: '1:833954155823:ios:97ad610864d77189bde5da',
    messagingSenderId: '833954155823',
    projectId: 'mentalzen-ammanuel',
    storageBucket: 'mentalzen-ammanuel.firebasestorage.app',
    iosBundleId: 'com.example.mentalZen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeCBf7iAMQ5Ur7WfEZ-F799cd0X2vf498',
    appId: '1:833954155823:web:173c2ead8b400b3dbde5da',
    messagingSenderId: '833954155823',
    projectId: 'mentalzen-ammanuel',
    authDomain: 'mentalzen-ammanuel.firebaseapp.com',
    storageBucket: 'mentalzen-ammanuel.firebasestorage.app',
  );
}
